Analysis template implementation complete
1053-August-Duet-Project-Registry/project-registry-gateway pull request #2
Opened 2021-07-20 21:12 UTC by jpbulloch5

The gateway now successfully implements the analysis.yml template from the project-registry-devops repo.

2021-07-20 21:33 UTC, BeoHawk25 submitted a review, later dismissed

2021-07-20 22:21 UTC, escalonn requested changes
cf. https://github.com/1053-August-Duet-Project-Registry/project-registry-account-microservice/pull/3#pullrequestreview-711097506

2021-07-21 05:03 UTC, escalonn requested changes
see https://github.com/1053-August-Duet-Project-Registry/project-registry-account-microservice/pull/3#pullrequestreview-711258014

2021-07-21 18:02 UTC, escalonn submitted a review, later dismissed

2021-07-21 18:02 UTC, escalonn commented on devops/azure-pipelines.yml
> +# "short-lived" branches and special analyisis is performed on pull-requests
spelling

2021-07-21 18:03 UTC, escalonn commented
see previous comment. @BeoHawk25 the pipeline is still not a required check on these PRs. arguably the sonar gate should be too.

2021-07-21 18:51 UTC, jpbulloch5 commented on devops/azure-pipelines.yml
> +# "short-lived" branches and special analyisis is performed on pull-requests
updated grammar/spelling on comment block

2021-07-21 21:29 UTC, escalonn approved these changes

2021-07-21 21:33 UTC, BeoHawk25 approved these changes

2021-07-21 21:34 UTC, merged